name: package on different operating systems
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Package-on-Macos:
    name: package on Macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: |
          pip install -r requirements.txt
          flet pack main.py

  Package-on-Windows:
    name: Package on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: |
          pip install -r requirements.txt
          flet pack main.py
